### ISSUE TITLE
Manual Testing

### ISSUE THREAD

**Issue by bognargabor99** [BME-MIT-IET/iet-hf2021-i08v2#8]
Ezen feladat célja a szoftvert egy felhasználó szemszögéből nézve kézzel tesztelni és így minél több hibát és bug-ot megtalálni. A tesztelés alapjául szolgálnak előre meghatározott tesztesetek, amelyek segítenek a szoftver funkcionalitásainak minél nagyobb halmazát átnézni.

**Comment by bognargabor99** [comment]
## Tesztesetek listája

1. Kimentés kötéllel
2. Jegesmedve meglátogatása
3. Betörik az unstable jégtabla
4. Eltörik a törékeny ásó
5. Hóvihar túlélése igluval
6. DivingSuit működik-e
7. Researcher képessége
8. Hagyunk valakit megfagyni
9. Játék megnyerése
10. Negative Testing

**Comment by balczer-dominik** [comment]
Tesztelem az alábbiakat:

1. Kimentés kötéllel
3. Betörik az unstable jégtábla
6. DivingSuit működik-e
9. Játék megnyerése
10. Negative Testing

**Comment by bognargabor99** [comment]
**Akkor enyém a maradék:**

- Jegesmedve meglátogatása
- Eltörik a törékeny ásó
- Hóvihar túlélése igluval
- Researcher képessége
- Hagyunk valakit megfagyni

**Comment by balczer-dominik** [comment]
Készítettem egy branch-et a teszteknek: https://github.com/BME-MIT-IET/iet-hf2021-i08v2/tree/manual-testing
